---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
golangci-lint:
  name: lint
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup Go
      uses: actions/setup-go/@v4
      with:
        go-version: 1.19
        cache: false
    - name: golangci-lint check
      uses: golangci/golangci-lint-action@v3
