
name: Run deploy.yaml

on:   # Events
  push:
    branches: [main]
      
jobs:
  Integrate-and-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go  
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1

    - name: Build 
      run: go build -v ./...

    - name: Test  
      run: go test -v ./...
      

    # - name: Deploy the app
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{secrets.PUBLIC_IP}}
    #     username: ${{secrets.USERNAME}}
    #     key: ${{secrets.SSH_KEY}}
    #     script: |
    #       echo "Connected to Server"
    #       docker compose stop ${{secrets.IMAGE_NAME}} 
    #       docker compose rm ${{secrets.IMAGE_NAME}}
    #       docker compose up -d
    #       echo "Deployment success"
