name: ci/cd

on: 
  push:
    branches: [main]

jobs:

  pull-request-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: run super linter
      uses: github/super-linter@v3
